apiVersion: v1
data:
  alertmanager.yaml: Imdsb2JhbCI6CiAgInJlc29sdmVfdGltZW91dCI6ICI1bSIKICAic2xhY2tfYXBpX3VybCI6ICJodHRwczovL2hvb2tzLnNsYWNrLmNvbS9zZXJ2aWNlcy9UOU5GVVNNTVcvQkMyRkFMWkZGL2V6RVR4eU8yS2t4OTRISlNLR2J4RGN5MSIKInJlY2VpdmVycyI6Ci0gIm5hbWUiOiAic2xhY2stbm90aWZpY2F0aW9ucyIKICAic2xhY2tfY29uZmlncyI6CiAgLSAiY2hhbm5lbCI6ICIjaGFyYm91ci10ZXN0LWdyYWZhbmEiCiAgICAidGV4dCI6ICJ7eyByYW5nZSAuQWxlcnRzIH19e3sgLkFubm90YXRpb25zLmRlc2NyaXB0aW9uIH19XG57eyBlbmQgfX0iCiJyb3V0ZSI6CiAgImdyb3VwX2J5IjoKICAtICJqb2IiCiAgImdyb3VwX2ludGVydmFsIjogIjVtIgogICJncm91cF93YWl0IjogIjMwcyIKICAicmVjZWl2ZXIiOiAic2xhY2stbm90aWZpY2F0aW9ucyIKICAicmVwZWF0X2ludGVydmFsIjogIjEyaCIKICAicm91dGVzIjoKICAtICJtYXRjaCI6CiAgICAgICJhbGVydG5hbWUiOiAiV2F0Y2hkb2ciCiAgICAicmVjZWl2ZXIiOiAic2xhY2stbm90aWZpY2F0aW9ucyI=
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
type: Opaque
