apiVersion: v1
data:
  alertmanager.yaml: Imdsb2JhbCI6CiAgInJlc29sdmVfdGltZW91dCI6ICI1bSIKICAic2xhY2tfYXBpX3VybCI6ICJodHRwczovL2hvb2tzLnNsYWNrLmNvbS9zZXJ2aWNlcy9UOU5GVVNNTVcvQkMyRkFMWkZGL2V6RVR4eU8yS2t4OTRISlNLR2J4RGN5MSIKInJlY2VpdmVycyI6Ci0gIm5hbWUiOiAic2xhY2stbm90aWZpY2F0aW9ucyIKICAic2xhY2tfY29uZmlncyI6CiAgLSAiY2hhbm5lbCI6ICIjaGFyYm91ci10ZXN0LWdhcmFmYW5hIgogICAgInRleHQiOiAie3sgcmFuZ2UgLkFsZXJ0cyB9fXt7IC5Bbm5vdGF0aW9ucy5kZXNjcmlwdGlvbiB9fVxue3sgZW5kIH19Igoicm91dGUiOgogICJncm91cF9ieSI6CiAgLSAiam9iIgogICJncm91cF9pbnRlcnZhbCI6ICI1bSIKICAiZ3JvdXBfd2FpdCI6ICIzMHMiCiAgInJlY2VpdmVyIjogInNsYWNrLW5vdGlmaWNhdGlvbnMiCiAgInJlcGVhdF9pbnRlcnZhbCI6ICIxMmgiCiAgInJvdXRlcyI6CiAgLSAibWF0Y2giOgogICAgICAiYWxlcnRuYW1lIjogIldhdGNoZG9nIgogICAgInJlY2VpdmVyIjogInNsYWNrLW5vdGlmaWNhdGlvbnMi
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
type: Opaque
